# -*- coding: utf-8 -*-
"""packaging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZ6JEmp1EwyYgeWc1X6aKy1RtqGvCwyP
"""

from google.colab import files

!cp "/content/drive/MyDrive/Colab Notebooks/Project/dataProc.py" .

# cp --help

!pip install datacompy

!pip install ruptures

import dataProc
# /content/drive/MyDrive/Colab Notebooks/Project/Copy of train (5).csv

from google.colab import drive
drive.mount('/content/drive')